version: "3.8"

networks:
  ecommerce-net:
    driver: bridge

volumes:
  database-vol:
  prometheus-vol:

services:
  
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - 8080:80
    networks:
      - ecommerce-net

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - 3000:3000
    networks:
      - ecommerce-net

  database:
    image: mongo:latest
    container_name: mongodb
    networks:
      - ecommerce-net
    restart: always
    volumes:
      - database-vol:/data/db
    environment:  
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:etc/prometheus/prometheus.yml
      - prometheus-vol:/prometheus
    command:
      - --web.config.file
      - /etc/prometheus/prometheus.yml


  # node_exporter:
  #   image: prom/node-exporter
  #   container_name: node_exporter
  #   command:
  #     - '--path.rootfs=/host'
  #   network_mode: host
  #   pid: host
  #   restart: unless-stopped
  #   volumes:
  #     - '/:/host:ro,rslave'