apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecommerce-mern
  labels:
    name: ecommerce-mern
spec:
  rules:
    - host: ecommerce.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: ecommerce-frontend
                port:
                  number: 80

    - host: ecommerce.com
      http:
        paths:
          - pathType: Prefix
            path: "/frontend"
            backend:
              service:
                name: ecommerce-frontend
                port:
                  number: 80

    - host: backend.ecommerce.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: ecommerce-backend
                port:
                  number: 80
