name: "Pipeline to build both frontend and backend images"

on:
    workflow_dispatch:
      branches:
        - master

env: 
    FRONTEND_DOCKER_IMAGE: sheriffexcel/ecommerce-frontend
    BACKEND_DOCKER_IMAGE: sheriffexcel/ecommerce-backend

jobs:
    
    build-frontend-image:
        runs-on: ubuntu-latest

        steps:
          
          - name: Checkout Codebase
            uses: actions/checkout@v4


          - uses: mr-smithers-excellent/docker-build-push@v6
            name: Build frontend Image
            with:
              image: ${{ env.FRONTEND_DOCKER_IMAGE }}
              tags: latest
              directory: ./client/
              dockerfile: ./client/Dockerfile
              registry: docker.io
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}

          - uses: mr-smithers-excellent/docker-build-push@v6
            name: Build Backend image
            with:
              image: ${{ env.BACKEND_DOCKER_IMAGE }}
              directory: ./server/
              dockerfile: ./server/Dockerfile
              tags: latest
              registry: docker.io
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}

  

          